### ISSUE TITLE
AGP 4.1.1:    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/R$drawable

### ISSUE THREAD

**Issue by cyangibm** [Archinamon/GradleAspectJ-Android#133]
Hi, 
Looks like the plugin would crash your app when you require to compile AGP 4.1.1 with NoClassDefFoundError, please help with this blocker:

AspectJ 4.3.0/4.2.1
AGP 4.1.1
Gradle 6.1.1/6.5.1

2021-01-19 15:17:06.608 10519-10519/com.cxa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cxa, PID: 10519
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/R$drawable;
        at androidx.appcompat.widget.AppCompatDrawableManager$1.<init>(AppCompatDrawableManager.java:63)
        at androidx.appcompat.widget.AppCompatDrawableManager.preload(AppCompatDrawableManager.java:57)
        at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:336)
        at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:286)
        at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:230)
        at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:554)
        at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:107)
        at android.app.Activity.attach(Activity.java:7893)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7478)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.R$drawable" on path: DexPathList[[zip file "/data/app/~~GyLFl18w-_vYxzan_N4p7Q==/com.cxa-YdwwJY1W7Bugh6V0o9WuuA==/base.apk"],nativeLibraryDirectories=[/data/app/~~GyLFl18w-_vYxzan_N4p7Q==/com.cxa-YdwwJY1W7Bugh6V0o9WuuA==/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.appcompat.widget.AppCompatDrawableManager$1.<init>(AppCompatDrawableManager.java:63) 
        at androidx.appcompat.widget.AppCompatDrawableManager.preload(AppCompatDrawableManager.java:57) 
        at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:336) 
        at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:286) 
        at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:230) 
        at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:554) 
        at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:107) 
        at android.app.Activity.attach(Activity.java:7893) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3295) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7478) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by sanren1024** [comment]
This problem occurs also in <code>4.3.0</code> with gradle plugin <code>4.1.0</code>.

Althougth problem fixed written in the changelog list at <code>4.2.1</code>.

When <code>4.3.0</code>, <code>4.2.1</code> versions used along with the gradle plugin <code>4.1.0</code>, problem occurs.

**Solution:**
Use <code>4.2.1</code> version with gradle plugin <code>4.0.0</code>.

Hope helpful.
